CREATE TABLE Currencies (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Users (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ApiKey TEXT NOT NULL,
    SecretKey TEXT NOT NULL
);

CREATE TABLE Wallets (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    CurrencyId INT NOT NULL REFERENCES Currencies(Id) ON DELETE CASCADE,
    Value NUMERIC(18, 8) NOT NULL DEFAULT 0,
    CONSTRAINT wallet_unique UNIQUE (UserId, CurrencyId)
);

CREATE TABLE Orders (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    CurrencyId INT NOT NULL REFERENCES Currencies(Id) ON DELETE CASCADE,
    Amount NUMERIC(18, 8) NOT NULL,
    Price NUMERIC(18, 8) NOT NULL,
    IsCompleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Transactions (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CurrencyId INT NOT NULL REFERENCES Currencies(Id) ON DELETE CASCADE,
    Date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    SenderId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    ReceiverId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Amount NUMERIC(18, 8) NOT NULL,
    Fee NUMERIC(18, 8) NOT NULL,
    OrderId UUID NOT NULL REFERENCES Orders(Id) ON DELETE CASCADE
);
